OFICIOS = {
    "Albañil": ["albañil", "albañila", "peón albañil", "peon albañil"],
    "Oficial Albañil": ["oficial albañil"],
    "Ayudante Albañil": ["ayudante albañil"],
    "Soldador": ["soldador", "soldadora", "soldadura"],
    "Soldador TIG": ["soldador tig", "tig"],
    "Soldador MIG/MAG": ["soldador mig", "soldador mag", "mig", "mag"],
    "Soldador Autógeno": ["autógeno", "oxigenista"],
    "Soldador de Cañerías": ["soldador cañerías", "soldador de cañeria"],
    "Soldador Eléctrico": ["soldador eléctrico", "soldador electrico"],
    "Electricista": ["electricista", "electricidad"],
    "Electricista de Obra": ["electricista de obra"],
    "Electricista de Baja Tensión": ["baja tensión", "baja tension"],
    "Electricista de Media Tensión": ["media tensión", "media tension"],
    "Electricista de Alta Tensión": ["alta tensión", "alta tension"],
    "Electricista Conexionista": ["conexionista"],
    "Electricista Montador": ["electricista montador"],
    "Plomero": ["plomero", "plomera", "plomería", "plomeria"],
    "Gasista": ["gasista", "gasista natural"],
    "Refrigeración": ["refrigeración", "refrigeracion", "aire acondicionado", "aa"],
    "Carpintero": ["carpintero", "carpintera", "carpintería", "carpinteria"],
    "Carpintero de Obra": ["carpintero obra"],
    "Carpintero de Encofrados": ["carpintero encofrados", "encofrador"],
    "Carpintero Metálico": ["carpintero metálico", "estructuras metálicas"],
    "Herrero": ["herrero", "herrera", "herrería", "herreria"],
    "Mecánico": ["mecanico", "mecánica", "mecanica"],
    "Mecánico Automotriz": ["mecánico automotriz", "mecanico automotriz", "automotor"],
    "Mecánico de Equipos Pesados": ["mecánico equipos pesados", "equipos pesados", "maquinaria pesada"],
    "Mecánico de Montaje": ["mecánico montaje"],
    "Mecánico de Plantas": ["mecánico plantas", "planta hormigonera"],
    "Pintor": ["pintor", "pintora", "pintura"],
    "Pintor de Obra": ["pintor obra"],
    "Chofer": ["chofer", "conductor", "chófer"],
    "Chofer de Camioneta": ["chofer camioneta", "conductor camioneta"],
    "Chofer de Automóvil": ["chofer автомovil", "conductor автомovil"],
    "Chofer de Camión": ["camión rígido", "camión articulado", "camion rigido", "camion articulado"],
    "Chofer de Volqueta": ["volqueta"],
    "Chofer de Microtransporte": ["microtransporte", "transporte personal"],
    "Chofer de Transporte de Áridos": ["transporte áridos", "transporte agregados"],
    "Chofer de Transporte de Hormigón": ["transporte hormigón", "transporte concreto"],
    "Chofer de Transporte de Combustible": ["transporte combustible"],
    "Chofer de Transporte de Equip Pesado": ["transporte equipos pesados"],
    "Amolador": ["amolador", "amoladora"],
    "Amolador de Herramientas": ["amolador herramientas"],
    "Encofrador": ["encofrador", "encofradora", "encofrados"],
    "Ferrero": ["ferrero", "ferrea", "fierrero", "armado de hierro", "armador de hierro"],
    "Yesero": ["yesero", "yesera"],
    "Mason": ["mason"],
    "Operador de Maquinaria": ["operador", "operador de maquinaria"],
    "Operador de Excavadora": ["excavadora"],
    "Operador de Retroexcavadora": ["retroexcavadora", "retropala"],
    "Operador de Topadora": ["topadora"],
    "Operador de Motoniveladora": ["motoniveladora"],
    "Operador de Cargadora Frontal": ["cargadora frontal", "cargadora"],
    "Operador de Compactador": ["compactador", "compactadora"],
    "Operador de Rodillo": ["rodillo estático", "rodillo neumático", "rodillo vibratorio", "rodillo"],
    "Operador de Autoelevador": ["autoelevador"],
    "Operador de Montacargas": ["montacargas"],
    "Operador de Grúa": ["operador de grúa", "grúa"],
    "Operador de Grúa de Pluma": ["grúa de pluma", "operador grua pluma"],
    "Operador de Hidrogrúa": ["hidrogrúa", "hidrogra", "operador hidrogrua"],
    "Operador de Plataforma": ["plataforma soportada", "plataforma pluma"],
    "Operador de Compresora": ["compresora", "compresor"],
    "Operador de Planta de Hormigón": ["planta hormigonera", "planta concreto"],
    "Operador de Vibradora": ["vibradora hormigon", "vibradora concreto"],
    "Operador de Demoledora": ["demoledora"],
    "Operador de Tractor": ["tractor"],
    "Operador de Radio": ["radio obra"],
    "Operador de Ultrasonido": ["ultrasonido"],
    "Operador de Prueba Hidráulica": ["prueba hidráulica"],
    "Operador de Tratamiento Térmico": ["tratamiento térmico"],
    "Tornero": ["tornero", "tornero fresador"],
    "Chapista": ["chapista", "chapa"],
    "Vidriero": ["vidriero", "vidrio"],
    "Colocador": ["colocador", "colocadora", "colocación pisos"],
    "Techador": ["techador", "techista", "techo"],
    "Impermeabilizador": ["impermeabilizador", "impermeabilización"],
    "Jardinero": ["jardinero", "jardinería"],
    "Seguridad": ["prevencionista", "prevención riesgos", "seguridad higiene", "higiene seguridad"],
    "Montador": ["montador", "montaje industrial"],
    "Montador de Estructuras": ["montador estructuras"],
    "Montador de Tanques": ["montador tanques"],
    "Montador en General": ["montador general"],
    "Tubero": ["tubero", "tuberías", "tuberia"],
    "Cañista": ["cañista", "cañerías"],
    "Instrumentista": ["instrumentista", "instrumentación"],
    "Dinamitero": ["dinamitero", "perforista", "cargador tiro"],
    "Machetero": ["machetero"],
    "Machetero Alpinista": ["machetero alpinista", "alpinista"],
    "Biselador": ["biselador"],
    "Curvador": ["curvador"],
    "Argonista": ["argonista"],
    "Banderillero": ["banderillero"],
    "Calchero": ["calchero"],
    "Carretonero": ["carretonero"],
    "Cepillero": ["cepillero"],
    "Cocinero": ["cocinero", "encargado cocina"],
    "Oxigenista": ["oxigenista"],
    "Pañolero": ["pañolero"],
    "Radiólogo": ["radiologo", "radiología"],
    "Revestidor": ["revestidor"],
    "Sereno": ["sereno"],
    "Soportista": ["soportista"],
    "Topógrafo": ["topografo", "topografía"],
    "Engrasador": ["engrasador"],
    "Cepillador": ["cepillador"],
}


def get_all_oficios():
    return list(OFICIOS.keys())


def get_keywords_oficio(oficio):
    return OFICIOS.get(oficio, [])